name: Build
on:
  - push
jobs:
  main:
    runs-on: ubuntu-latest
    container: nvidia/cuda:12.4.1-cudnn-devel-ubuntu22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install build dependencies
        run: |
          apt update --yes && apt install --yes ninja-build
          python -m pip install torch build wheel setuptools
      - run: python -m build --no-isolation --config-setting="--build-option=--cpp_ext" --config-setting="--build-option=--cuda_ext" ./
      - name: Upload distributions
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/
